Repository Talend/tdi-studio-se, pull requests merged in 2018-10, with the labels that each got.

#2748 fix(TDI-41119): add more condition to use edtftpj library
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
Labels: Need review

#2753 Dsylaiev/tdi 40911 remove redundant 11 6 oracle version
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleInput/tAmazonOracleInput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleInput/tAmazonOracleInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleInput/tAmazonOracleInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleRow/tAmazonOracleRow_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleRow/tAmazonOracleRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleRow/tAmazonOracleRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleMap/tELTOracleMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleMap/tELTOracleMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleBulkExec/tOracleBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleInput/tOracleInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutputBulkExec/tOracleOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutputBulkExec/tOracleOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleRow/tOracleRow_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleRow/tOracleRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleRow/tOracleRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCDELT/tOracleSCDELT_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCDELT/tOracleSCDELT_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCDELT/tOracleSCDELT_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSP/tOracleSP_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSP/tOracleSP_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSP/tOracleSP_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
  main/plugins/org.talend.designer.components.localprovider/components/templates/slowly_change_dimension.skeleton
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UseOracle11VersionInsteadOfRemoved.java
Labels: Need review

#2752 fix(TCOMP-925): columns order in tcompv1 tables
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ListPropertyNode.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/PropertyNode.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
Labels: Need review

#2757 fix(TUP-20854): NPE show in error log when add reference project
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ArtifactRepositoryShareSettingPage.java
Labels: buildme

#2732 feat(TDI-40958): update salesforce api to 43.0
  main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml
Labels: Need review

#2763 fix(TDI-41119): add more condition to use edtftpj library (#2748)
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
Labels: Need review

#2620 Mbasiuk/tdi 40846 date validation fix
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_messages.properties
Labels: Need review

#2758 fix(TDI-41063): change count NB lines logic
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
Labels: Need review

#2769 fix(TDI-41137): Revert change mistake in property message"
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
Labels: Need review

#2779 fix(TUP-20796): [bug] there are errors after click Property Type: repository button to choose db
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/provider/TaCoKitMetadataContentProvider.java
Labels: Build running

#2792 feat(TDI-40958): update salesforce default endpoint to 44.0
  main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveBulkExec/tSalesforceWaveBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSalesforceWaveOutputBulkExec/tSalesforceWaveOutputBulkExec_java.xml
Labels: Need review

#2768 fix(TDI-41043): SFTP tFTPFileList full file info fix Backport to 7.0
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Labels: Need review

#2810 fix(TDI-40504): Revert "Dsylaiev/tdi 40504 implement move to current …
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_main.javajet
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UncheckMoveToRemoteDirSFTP.java
Labels: Need review

#2814 fix(TUP-20980):tMysqlInput --> "Guess schema" not show the warning message.
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractGuessSchemaProcess.java
Labels: Build running

#2811 fix(TBD-7334) check tContexLoad is not null prior to use
  main/plugins/org.talend.designer.components.localprovider/components/tContextLoad/tContextLoad_main.javajet
Labels: Need review

#2851 bugfix(TUP-20905)Edit resource wizard show "Ok" when open the page.
  main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/NewRouteResourceWizardPage.java
Labels: Build running

#2858 fix(TUP-20913)Remote project:job run use old data if not run the child
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
  main/plugins/org.talend.repository.resource/src/org/talend/repository/resource/ui/wizards/EditRouteResourcePropertiesWizard.java
Labels: Build running

#2819 fix(TDI-41162): correct file detail for FTP and FTPs mode
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Labels: Need review
