Repository Talend/tdi-studio-se, pull requests merged in 2018-07, with the labels that each got.

#2477 fix(TDI-40674): Add property to avoid windows-separator replacement
  main/plugins/org.talend.designer.components.localprovider/components/tSCPGet/tSCPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSCPGet/tSCPGet_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSCPGet/tSCPGet_messages.properties
Labels: Need review

#2482 fix(TDI-34091): add cid to name of config file
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
Labels: Need review

#2495 Rvoievidko/tdi 34091 parallel subjobs in t greenplum gp load
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
Labels: Need review

#2505 TUP-20433 - tHMap throw npe when connect to output but haven't config it
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
Labels: Build running

#2475 feat(TDI-38814): tCreateTable support snowflake
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
Labels: Need review

#2397 feat(TDI-40559): Fix appName parameter in jdbc url
  main/plugins/org.talend.designer.components.localprovider/components/tSQLDWHBulkExec/tSQLDWHBulkExec_begin.javajet
Labels: Need review

#2242 Add Commandline test product
  main/features/org.talend.tos.core.feature/.project
  main/features/org.talend.tos.core.feature/build.properties
  main/features/org.talend.tos.core.feature/feature.xml
  main/features/org.talend.tos.core.feature/pom.xml
  main/features/org.talend.tos.feature/feature.xml
  pom.xml
Labels: Work in progress

#2491 fix(TUP-20361):the report path is not correct.
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/audit/AuditManager.java
Labels: Build running

#2517 Revert "fix(TDI-36144):SCD deactivates for type 2 records even if an inserting record is rejected(#2425)"
  main/plugins/org.talend.designer.components.localprovider/components/tDB2SCD/tDB2SCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tDB2SCD/tDB2SCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tDB2SCD/tDB2SCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tInformixSCD/tInformixSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tInformixSCD/tInformixSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInformixSCD/tInformixSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tIngresSCD/tIngresSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tIngresSCD/tIngresSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tIngresSCD/tIngresSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlSCD/tMysqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlSCD/tMysqlSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlSCD/tMysqlSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaSCD/tNetezzaSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaSCD/tNetezzaSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaSCD/tNetezzaSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSCD/tOracleSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelSCD/tParAccelSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelSCD/tParAccelSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelSCD/tParAccelSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCD/tPostgresPlusSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCD/tPostgresPlusSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCD/tPostgresPlusSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCD/tSybaseSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCD/tSybaseSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseSCD/tSybaseSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataSCD/tTeradataSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataSCD/tTeradataSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataSCD/tTeradataSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaSCD/tVerticaSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaSCD/tVerticaSCD_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaSCD/tVerticaSCD_messages.properties
Labels: Need review

#2546 fix(TDI-39567): add tabs / improve code redability
  main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet
Labels: Need review

#2547 fix(TDI-40729): tCreateTable spelling error
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages_en.properties
Labels: Need review

#2537 feat(TDI-40574): tSnowflakeOB and tSnowflakeBE
  main/plugins/org.talend.designer.unifiedcomponent/src/main/java/org/talend/designer/unifiedcomponent/unifier/snowflake/unifier.json
Labels: Need review

#2557 fix(TDI-40815): Compilation issue with tSalesforceOutput component with reject link
  main/plugins/org.talend.designer.codegen/jet_stub/generic/component_process_data_begin.javajet
Labels: Need review
