Repository Talend/tdi-studio-se, pull requests merged in 2018-12, with the labels that each got.

#3043 Dsylaiev/tdi 41440 update jackson databind version in custom lib
  main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml
Labels: Need review

#3034 fix(TUP-21245)faile to check JDBC connection with context Migrate from
  main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/migration/NewJDBCConnectionMigrationTask.java
Labels: Build running

#3056 bugfix(TUP-21356):"talend-bigdata-launcher-1.2.0-20170410.jar" not fo…
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/BigDataJobUtil.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
Labels: Build running

#3060 Dsylaiev/tdi 41507 backport to 71
  main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml
Labels: backport

#3062 fix(TUP-21167):Install Additional Packages has no available modules.
  main/plugins/org.talend.designer.core/src/main/java/messages.properties
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PerformancePreferencePage.java
Labels: Build running

#2468 fix(TDI-32185): fix limit for dynamic columns
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/DecrementLimitTFileInputDelimitedTDI32185.java
Labels: Need review

#3071 Dchmyga/tdi 41512 backport to 6.4
  main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/src/main/java/org/talend/archive/IntegrityUtil.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/checkArchive.jar
  main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_messages.properties
  main/plugins/org.talend.libraries.custom/pom.xml
Labels: Need review

#3025 fix(TDI-41404): Avoid 64kb method issue when too many context paramet…
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review

#3070 fix(TUP-21396)keeping popup for running a job after adding a var in CONEXT GROUP
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
Labels: Build running

#3087 Dsylaiev/tdi 41404 fix 64kb issue t run job context
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
Labels: Need review

#3097 fix(TUP-9814):SCD component add a warning message if the source key is empty.
  main/plugins/org.talend.designer.core/src/main/java/messages.properties
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/nodes/Node.java
Labels: Build running

#3093 fix(TDI-41176):'File Json' > 'Input Json' metadata does not show parent values in Preview with JsonPath (#2820) (#2922)
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/read_by_jsonpath_process.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_messages.properties
  main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/dnd/JSONDragAndDropHandler.java
  main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/shadow/FileInputJsonNode4Input.java
Labels: Need review

#3111 bugfix(TUP-19612): Save Query: String in default pop up dialog is tru…
  main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLPropertyDialog.java
Labels: Build running

#3096 fix(TDI-41556): Redshift driver name was changed
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_begin.javajet
Labels: Need review
