Repository Talend/tdi-studio-se, pull requests merged in 2018-11, with the labels that each got.

#2869 fix(TUP-21005)In studio Java Debugging of Routes fails
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
Labels: Build running

#2885 fix(TUP-20765)"Web-app Url" is read-only and empty after clicking "+";
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java
Labels: Build running

#2890 Fixed(TUP-20927)Automatic scrolling in execution console prevent uppe…
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
Labels: Build running

#2862 fix(TUP-21026): empty schema in suggestable method
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaActionParameter.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SchemaElementParameter.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
Labels: Reviewing

#2917 Mbasiuk/tdi 40846 date validation fix (#2620)
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_messages.properties
Labels: Need review

#2918 Mbasiuk/tdi 40846 date validation fix (#2620)
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSchemaComplianceCheck/tSchemaComplianceCheck_messages.properties
Labels: Need review

#2896 fix(TUP-20516):Audit: Improve: Better Use an Error message if connection isn't successful
  main/plugins/org.talend.repository/src/main/java/messages.properties
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/AuditProjectSettingPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/audit/AuditManager.java
Labels: Build running

#2921 fix(TDI-41176):'File Json' > 'Input Json' metadata does not show parent values in Preview with JsonPath (#2820)
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/read_by_jsonpath_process.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_messages.properties
  main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/dnd/JSONDragAndDropHandler.java
  main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/shadow/FileInputJsonNode4Input.java
Labels: Need review

#2922 fix(TDI-41176):'File Json' > 'Input Json' metadata does not show parent values in Preview with JsonPath (#2820)
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/read_by_jsonpath_process.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tExtractJSONFields/tExtractJSONFields_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/tFileInputJSON_messages.properties
  main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/dnd/JSONDragAndDropHandler.java
  main/plugins/org.talend.repository.json/src/org/talend/repository/json/ui/shadow/FileInputJsonNode4Input.java
Labels: Need review

#2894 bugfix(TUP-21058):Snowflake ELTJDBCInput/Output
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
Labels: Build running

#2959 Fix(TUP-21161)can't use the up-arrow button or scroll bar to locate at
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
Labels: Build running

#2952 feat(TDI-40805): add JDBC properties to Java api mode
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastExport/tTeradataFastExport_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastExport/tTeradataFastExport_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataFastExport/tTeradataFastExport_messages_en.properties
Labels: Need review

#2963 fix(TUP-20993)The prompt box title and icon are inconsistent
  main/plugins/org.talend.designer.core/src/main/java/messages.properties
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
Labels: Build running

#2901 Rvoievidko/tdi 41297 mark as duplicated third party apps
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Connection/tAS400Connection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Input/tAS400Input_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Row/tAS400Row_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_messages.properties
Labels: Need review

#2817 fix(TDI-40441): tMomXXX components to connect to SSL enabled Websphere MQ channel (#2341 & #2385)
  main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomConnection/tMomConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMomInput/tMomInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomInput/tMomInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomMessageIdList/tMomMessageIdList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomOutput/tMomOutput_messages.properties
Labels: Need review

#2984 bugfix(TUP-21164):Context is not recognized as context variable in ELT
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
Labels: Build running

#3000 fix(TUP-21094)Job can not be run after the first time I set tELTMap and
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/ProcessUpdateManager.java
Labels: Build running

#3022 feat(TUP-21109): Deprecate build of sources from Build job menu
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/JobScriptsExportWizardPage.java
Labels: Build running
