Repository Talend/tdi-studio-se, pull requests merged in 2019-12, with the labels that each got.

#4177 Vyu/tdi 40599 enable use hint in merge
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_messages.properties
Labels: Need review

#3615 Fix(TDI-42424):Improve for tELTPostgresqlOutput generate wrong update
  main/plugins/org.talend.designer.components.localprovider/components/tELTPostgresqlOutput/tELTPostgresqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTPostgresqlOutput/tELTPostgresqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTPostgresqlOutput/tELTPostgresqlOutput_messages.properties
Labels: Need review

#4192 fix(TDI-43085): Bump jackson version to 2.10.1
  main/plugins/org.talend.designer.components.libs/libs_src/talend-httputil/pom.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRListInstances/tAmazonEMRListInstances_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRResize/tAmazonEMRResize_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBoxConnection/tBoxConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBoxCopy/tBoxCopy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBoxDelete/tBoxDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBoxGet/tBoxGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBoxList/tBoxList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBoxPut/tBoxPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tDropboxConnection/tDropboxConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tDropboxDelete/tDropboxDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tDropboxGet/tDropboxGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tDropboxList/tDropboxList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tDropboxPut/tDropboxPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/tSQSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageChangeVisibility/tSQSMessageChangeVisibility_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageDelete/tSQSMessageDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueCreate/tSQSQueueCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueDelete/tSQSQueueDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueList/tSQSQueueList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueuePurge/tSQSQueuePurge_java.xml
Labels: Need review

#4214 fix(TUP-25453)color setting for log4j2
  main/plugins/org.talend.designer.runprocess/resources/log/log4j2.properties_template
Labels: Build running

#4246 fix(TUP-24148): tNetsuiteInput throws cast error when switching from use tNetsuiteConnection to use this component
  main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
Labels: buildme

#4242 fix(TUP-25411):Table name and field should in double quotes in tELTPostgresqlMap.
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java
Labels: buildme

#4249 fix(TUP-25541)tMap TUJs are broken for the ClassNotFound
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
Labels: buildme

#4258 fix(TUP-25575):Upgrade tacokit to 1.1.15.
  main/plugins/org.talend.sdk.component.studio-integration/pom.xml
Labels: buildme

#4233 Fix(TDI-43323):Fix issue of duplicated variables.
  main/plugins/org.talend.designer.components.localprovider/components/tNormalize/tNormalize_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tNormalize/tNormalize_main.javajet
Labels: Need review

#4260 fix(TUP-25502): import dialog i18n error
  main/plugins/org.talend.sdk.component.studio-integration/META-INF/MANIFEST.MF
  main/plugins/org.talend.sdk.component.studio-integration/build.properties
  main/plugins/org.talend.sdk.component.studio-integration/plugin.properties
Labels: buildme

#4152 bugfix(TUP-22500):jars already existed on nexus still try to upload
  main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/viewer/handlers/RoutineImportHandler.java
Labels: buildme

#4259 Jzhang/bugfix/tup 25572 avoid loop method on log4j
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/DesignerCoreService.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/bigdata/BigDataJavaProcessor.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessorUtilities.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/UpdateLog4jJarUtils.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/CheckLogManagerTest.java
Labels: Build running

#4285 fix(TUP-24727):Use shortcut F1 to search help document on component then throw errors
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/context/TaCoKitContextProvider.java
Labels: Build running

#4241 Mbasiuk/tdi 43095 improve set section
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_messages.properties
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
Labels: Need review
