Repository Talend/tdi-studio-se, pull requests merged in 2019-10, with the labels that each got.

#3985 TESB-27081 SOAP Action missing while calling a SOAP WebService through tESBConsumer
  main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
  main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
Labels: Build running

#3995 fix(TDI-42969): change logic to retrieve detailed filename
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Labels: Need review, backport

#3969 Fix(TDI-41289):Add reuse tS3Connection.
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_messages.properties
Labels: Need review

#3876 Add talend proxy library
  main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/ProxyCreds.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/ProxyHolder.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/TalendProxyAuthenticator.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-proxy/src/main/java/org/talend/proxy/TalendProxySelector.java
Labels: Need review

#3899 Dsylaiev/tdi 40977 add setting local properties for t set proxy
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftps_connect.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/sftp_connect.javajet
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: Need review

#4039 fix(TUP-24607)Not able to see the component error in the Studio Desig…
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessErrorUtil.java
Labels: Build running

#4052 fix(TDI-40977): Fix https proxy usage for custom mode
  main/plugins/org.talend.designer.components.localprovider/components/tSetProxy/tSetProxy_main.javajet
Labels: Need review

#4078 fix(TDI-42015): change label for hex and octal numbers
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_messages.properties
Labels: Need review
