Repository Talend/tdi-studio-se, pull requests merged in 2019-07, with the labels that each got.

#3653 fix(TDI-42536): tFileFetch NTLM PROXY issues
  main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_main.javajet
Labels: Work in progress

#3691 fix(TUP-23790):Can't guess schema for metadata item(delimited/positional/regex/excel/ldif/ldap)
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
Labels: Build running

#3702 fix(TDI-42436): copy Redshift components to cloud folder
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
Labels: Need review

#3677 Fix(TDI-42572):Improvement for generating correct format to Exasol
  main/plugins/org.talend.designer.components.libs/libs_src/talend-db-exasol-util/src/main/java/org/talend/database/exasol/imp/EXABulkUtil.java
  main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXABulkExec/tEXABulkExec_messages.properties
Labels: Need review

#3733 fix(TDI-42457): correct Postgre supported DB version
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusBulkExec/tPostgresPlusBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusInput/tPostgresPlusInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutputBulkExec/tPostgresPlusOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusRow/tPostgresPlusRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCD/tPostgresPlusSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCDELT/tPostgresPlusSCDELT_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlInput/tPostgresqlInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutputBulkExec/tPostgresqlOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlRow/tPostgresqlRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCDELT/tPostgresqlSCDELT_messages.properties
Labels: Need review

#3713 (feature(TBD-8945): added drop table checkbox to OAuth authentication…
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
Labels: Build running

#3756 Dsylaiev/tdi 37257 timeout sftp
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/sftp_connect.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_messages.properties
Labels: Need review

#3766 feat(TDI-36668): Add possibility to write xlsm files
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_messages.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review
