Repository Talend/tdi-studio-se, pull requests merged in 2019-01, with the labels that each got.

#3136 bugfix(TUP-21564):tMap settings - the "Options" window pop-up not
  main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/dialog/ListStringValueDialog.java
Labels: Build running

#3123 Dsylaiev/tdi 41404 backport to 71
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review, backport

#3122 fix(TDI-41404): Avoid 64kb method issue when too many context paramet…
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review, backport

#3124 Dsylaiev/tdi 41404 backport to 65
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review, backport

#3125 Dsylaiev/tdi 41404 backport to 64
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review, backport

#3126 Dsylaiev/tdi 41404 backport to 63
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review, backport

#3127 Dsylaiev/tdi 41404 backport to 62
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review, backport

#3138 fix(TDI-41556): Redshift driver name was changed (Backport to 7.1) (#3096)
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_begin.javajet
Labels: Need review, backport

#3137 fix(TDI-41581): change MySQL db name recognition
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
Labels: Need review

#3163 fix(TDI-41469): check zip integrity die on error
  main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_begin.javajet
Labels: Need review

#3174 fix(TUP-21532):fix StandardJobStandaloneBuildProviderTest
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/build/StandardJobStandaloneBuildProviderTest.java
Labels: Build running

#3196 fix(TUP-2382):The Connection Window should NOT show the exact number of
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionFormComposite.java
Labels: Build running

#3202 fix(TDI-41678): Upgrade custom lib version to avoid compile error
  main/plugins/org.talend.designer.components.libs/libs_src/commons-net-ftps-proxy/pom.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: Need review
