Repository Talend/tdi-studio-se, pull requests merged in 2020-07, with the labels that each got.

#4890 Dsylaiev/tdi 44349 backport ftp feature correctly
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
Labels: Need review, backport

#4891 Add contributor's real name.
  CONTRIBUTORS.md
Labels: Need review

#4892 Add contributor's real name.
  CONTRIBUTORS.md
Labels: Need review, backport

#4770 fix(TUP-27352):Traces enabled by default when using Memory Run
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/connections/Connection.java
Labels: Build running

#4901 fix(TUP-26347):Bug in tMap component using Talend Studio on Mac
  main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/DataMapTableView.java
Labels: Build running

#4906 add junit caused by TDI-44284
  test/plugins/org.talend.designer.unifiedcomponent.test/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommandTest.java
Labels: Build running

#4907 Jzhang/junit/tdi 44284
  test/plugins/org.talend.designer.unifiedcomponent.test/src/main/java/org/talend/designer/unifiedcomponent/controller/ChangeComponentCommandTest.java
Labels: Build running

#4878 feat(TUP-27680)Can't use the database "MAPPING" parameter to decide the component UI if show
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
Labels: Build running

#4884 feat(TDI-44215): Dynamic Schema for Vertica Bulk - Integrate in Studio monthly release of July
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForBulk.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/createTableFromDynamicInBulkExec.javajet
Labels: Need review, backport

#4839 feat(TDI-38246): add new auth type to Google Storage family
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/main/java/org/talend/gs/util/GSObjectUtil.java
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/java/util/GSObjectUtilTest.java
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/resources/dirWithThreeFiles/1.csv
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/resources/dirWithThreeFiles/2.csv
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/resources/dirWithThreeFiles/3.csv
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/resources/dirWithThreeFiles/inner/1.csv
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/resources/empty.csv
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSClose/tGSClose_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_messages_en.properties
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/GoogleStorageSetDefaultAuthTypeMigrationTask.java
Labels: Need review

#4927 fix(TDI-44453):tAdvancedFileOutputXML issue after upgrading to 7.3.1
  main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.inc.javajet
Labels: Need review

#4940 fix(TDI-44453):tAdvancedFileOutputXML issue after upgrading to 7.3.1
  main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.inc.javajet
Labels: Need review

#4780 fix(TDI-44202): tCreateTable add support of Sybase
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
Labels: Need review

#4909 feat(TDI-44466): add service account support for BulkExec and Output
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutput/tBigQueryOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutput/tBigQueryOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutput/tBigQueryOutput_messages_en.properties
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/BigQuerySetDefaultAuthTypeForGSMigrationTask.java
Labels: Need review

#4908 feat(TDI-44476): Add parquet support for tReshiftUnload
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_messages.properties
Labels: Need review

#4943 feat(TDI-44476): Add parquet support for tReshiftUnload (#4908)
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_messages.properties
Labels: Need review, backport

#4944 fix(TDI-44561): fix compile error when dieOnError is checked
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_main.javajet
Labels: Need review

#4949 fix(TDI-44562): replace all backslashes in GS path
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/main/java/org/talend/gs/util/GSObjectUtil.java
  main/plugins/org.talend.designer.components.libs/libs_src/google-storage-utils/src/test/java/util/GSObjectUtilTest.java
Labels: Need review

#4922 fix(TUP-27601):NPE when try to copy-paste database component inside the job
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
Labels: Build running

#4979 fix(TDI-44579): Hide encrypt button for parquet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
Labels: Need review

#4990 fix(TDI-44579): Hide encrypt button for parquet (#4979)
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
Labels: backport

#4989 fix(TUP-19440)Search for new tDB* components are not bringing best
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/TalendEditorPaletteFactoryTest.java
Labels: Build running

#5000 TESB-29133 Update dom4j to 2.1.3
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Labels: Build running

#5008 fix(TDI-44512): Bump mscrm lib version for localprovider components (…
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
  main/plugins/org.talend.libraries.crm/pom.xml
Labels: Need review, backport
