Repository Talend/tdi-studio-se, pull requests merged in 2020-05, with the labels that each got.

#4647 fix(TDI-44093): Fix processing of quoted strings
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
Labels: Need review

#4638 fix(TDI-44074): Fix performance for date mssql
  main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
Labels: Need review

#4639 bugfix(TUP-26186):Use of the operators =, <=, <, >=, >, <> instead of
  main/plugins/org.talend.designer.dbmap/plugin.xml
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/operator/DbOperator.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/operator/IDbOperator.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/teradata/TeradataDbOperatorValues.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/migration/DbOperatorMigrationTask.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/teradata/TeradataDbOperatorValuesTest.java
Labels: Build running

#4665 fix(TUP-27066)test failed in "Expression Builder" dialog
  main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNode.java
Labels: Build running

#4633 bugfix(TUP-26958):Test case: possible to remove input / output node
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ConnectionReconnectCommand.java
Labels: Build running

#4680 fix(TDI-43812): filemask not supported by tFTPRename
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_messages.properties
Labels: Need review

#4607 feat(TDQ-17831) update tPersonator component with new fields IPAddress
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/UpdatetPersonatorOutputSchemaTask.java
Labels: Build running

#4662 Fix(TDI-30698): Remove lines of spaces between elements in output XML.
  main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_end.javajet
Labels: Need review

#4688 bugfix(TUP-26002):Reject Schema is original schema, not changed schema
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeMetadataCommand.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ExternalNodeChangeCommand.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/CopyMetadataTableUtil.java
Labels: Build running

#4681 feat(TDI-44179):support copy command in Azure synapse bulk load
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeDefaultLoadMethod4tSynapseBulkExec.java
Labels: Build running, Need review

#4684 fix(TDI-44128): Update axis2 dependency CVE
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
Labels: Need review

#4686 feat(TESB-24998): Add context support for data services and routes
  main/plugins/org.talend.repository/resources/job-rest-template.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Labels: Build running

#4691 TUP-16067 Don't allow drag route to job.
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
Labels: Build running

#4683 Fix(TDI-44173): Fix for inner element creation in Loop element.
  main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.javajet
Labels: Need review

#4696 fix(TUP-26924):tELTXXX: link name won't be updated after updating "default table name" in tELTInput.
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
Labels: Build running

#4716 TUP-14559 change the toolbar button's tool tip, change the modification query dialog's title,keep consistent with tooltip of toolbar button.
  main/plugins/org.talend.sqlbuilder/src/main/java/messages.properties
  main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/actions/GUIModificationQueryAction.java
  main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/AbstractSQLEditorComposite.java
  main/plugins/org.talend.sqlbuilder/src/main/java/org/talend/sqlbuilder/ui/SQLBuilderDesignerComposite.java
Labels: Build running

#4699 fix(TDI-44105): CVE update xmlrpc-common version
  main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
Labels: Need review

#4703 fix(TDI-44104): update xmlrpc-common version
  main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml
Labels: Need review

#4711 fix(TDI-44115): update xmlrpc-client version
  main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml
Labels: Need review

#4710 fix(TDI-44169): update xmlrpc-client version
  main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
Labels: Need review

#4715 Dsylaiev/tdi 43605 fix using existing connection with rest tcompv0 (#…
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplate/tSQLTemplate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateAggregate/tSQLTemplateAggregate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateCommit/tSQLTemplateCommit_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateFilterColumns/tSQLTemplateFilterColumns_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateFilterRows/tSQLTemplateFilterRows_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateMerge/tSQLTemplateMerge_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateRollback/tSQLTemplateRollback_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_main.javajet
Labels: backport

#4629 Fix(TDI-30505): Do not log if no autocommit.
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tHSQLDbOutput/tHSQLDbOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInformixOutput/tInformixOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tIngresOutput/tIngresOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInterbaseOutput/tInterbaseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMaxDBOutput/tMaxDBOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaOutput/tNetezzaOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelOutput/tParAccelOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLiteOutput/tSQLiteOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataOutput/tTeradataOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseOutput/tVectorWiseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/DBOutputEndGlobalVars.javajet
Labels: Need review

#4753 fix(TDI-44115): remove xmlrpc_3.1.2 from studio
  main/plugins/org.talend.libraries.xml/lib/xmlrpc-client-3.1.2.jar
  main/plugins/org.talend.libraries.xml/lib/xmlrpc-common-3.1.2.jar
Labels: Need review

#4743 fix(TDI-44269): Set Outline ERROR_MESSAGE values.
  main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileDelete/tFileDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
Labels: Need review

#4759 fix(TDI-44269): Set Outline ERROR_MESSAGE values.
  main/plugins/org.talend.designer.components.localprovider/components/tFileCopy/tFileCopy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileDelete/tFileDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_begin.javajet
Labels: Need review, backport
