Repository Talend/tdi-studio-se, pull requests merged in 2020-10, with the labels that each got.

#5207 fix(TDI-44880): Add ERROR_MESSAGE in components.
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
Labels: Need review

#5305 fix(TDI-44880): backport fix to "maintenance/7.1" branch.
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
Labels: Need review, backport

#5306 fix(TDI-44880): backport fix to "maintenance/7.2" branch.
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
Labels: Need review, backport

#5308 fix(TDI-44880): backport fix into "master" branch.
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSendMail/tSendMail_main.javajet
Labels: Need review, backport

#5229 fix(TDI-44893): upgrade libraries, update code, remove old libs
  main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/soap/src/main/java/org/talend/soap/SOAPUtil.java
  main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: Need review

#5273 fix(TDI-44839): CVE - Update postgresql driver
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusBulkExec/tPostgresPlusBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusInput/tPostgresPlusInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusRow/tPostgresPlusRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCD/tPostgresPlusSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCDELT/tPostgresPlusSCDELT_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlInput/tPostgresqlInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlRow/tPostgresqlRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCDELT/tPostgresqlSCDELT_java.xml
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java
Labels: Need review

#5353 fix(TDI-44839): Backport - update POSTGRESQL driver
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusBulkExec/tPostgresPlusBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusInput/tPostgresPlusInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusRow/tPostgresPlusRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCD/tPostgresPlusSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusSCDELT/tPostgresPlusSCDELT_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlInput/tPostgresqlInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlRow/tPostgresqlRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCD/tPostgresqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlSCDELT/tPostgresqlSCDELT_java.xml
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/StatsAndLogsConstants.java
Labels: Need review, backport

#5303 fix(TDI-44957): tSSH timeouts use
  main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet
Labels: Need review

#5354 fix(TDI-44957): Backport - tSSH timeouts use
  main/plugins/org.talend.designer.components.localprovider/components/tSSH/tSSH_begin.javajet
Labels: Need review, backport

#5364 chore(TDI-45008):tFileOutputDelimited, 'Use OS line separator as row separator when CSV Row separator is set to CR, LF or CRLF' does not work properly
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_messages_ja.properties
Labels: Need review

#5371 fix(TDI-44893): added missing dependency
  main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: needs review

#5372 fix(TDI-44893): update component, and localprovider
  main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: needs review

#5307 fix(TDI-44897): Add exit code of GPLoad
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
Labels: Need review

#5304 fix(TDI-44896): Get nbline from stdout of gpload
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
Labels: Need review

#5389 fix(TDI-44896): Get nbline from stdout of gpload (#5304)
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
Labels: backport

#5399 fix(TDI-45015): tFileInputMail - slow attachments retrieval.
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Labels: Need review

#5420 fix(TDI-45015): Backport (741) - tFileInputMail retrieves attachments very slow.
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Labels: Need review, backport

#5421 fix(TDI-45015): backport fix into "maintenance/7.2" branch
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Labels: Need review, backport

#5415 chore(TDI-44004): update talend-ws lib
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tWebService/tWebService_java.xml
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: Need review

#5408 chore(TDI-45022): backport Apache POI update to "master"
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.excel/build.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5430 fix(TDI-44087): Update Xstream to 1.4.11.1 version
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: Need review

#5435 chore(TDI-42384): remove old neo4j repo from pom
  main/plugins/org.talend.designer.components.libs/libs_src/neo4j-talend-component/pom.xml
Labels: Need review

#5426 fix(TDI-45023): Update tJasper* components to use Apache POI 4.1.2
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_main.javajet
Labels: Need review

#5439 fix(TDI-45023): Backport - tJasper to use Apache POI 4.1.2
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_main.javajet
Labels: Need review, backport

#5445 fix(TDI-45015): removed streams declaration outside try-with-resources
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Labels: Need review

#5446 Revert "Fix(TDI-44173): Fix for inner element creation in Loop element."
  main/plugins/org.talend.designer.components.localprovider/components/tAdvancedFileOutputXML/tAdvancedFileOutputXML_begin.javajet
Labels: Need review
