Repository Talend/tdi-studio-se, pull requests merged in 2020-11, with the labels that each got.

#5427 chore(TDI-44994): bump library version
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
Labels: Need review

#5491 feat(TUP-25235):tELTTeradataMap : allow to rename the alias.
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/tableentry/TableEntryLocation.java
Labels: Build running

#5490 feat(TUP-25235):tELTTeradataMap : allow to rename the alias.
  main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/postgres/PostgresGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/TableEntriesManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/tableentry/TableEntryLocation.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/AliasDialog.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/DataMapTableView.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarInputZone.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/managers/MapperManagerTest.java
Labels: Build running

#5532 Fix/TDI45204_IncorrectOutlineFortFileFetch
  main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_messages.properties
Labels: Need review

#5533 Fix/TDI45204_IncorrectOutlineFortFileFetch (#5532)
  main/plugins/org.talend.designer.components.localprovider/components/tFileFetch/tFileFetch_messages.properties
Labels: backport

#5528 chore(TDI-45213): upgrade ascii doctor to prevent snakeyaml CVE
  main/plugins/org.talend.sdk.component.studio-integration/pom.xml
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/AsciidoctorService.java
Labels: Need review

#5559 fix(TUP-29090):[7.2.1] Extra plus '+' signs in generated SQL
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/utils/DataMapExpressionParserTest.java
Labels: Build running

#5558 fix(TUP-29090):[7.2.1] Extra plus '+' signs in generated SQL
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DataMapExpressionParser.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/utils/DataMapExpressionParserTest.java
Labels: Build running

#5473 feat(TDI-44915) access token feature
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutput/tBigQueryOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutput/tBigQueryOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQuerySQLRow/tBigQuerySQLRow_process_data_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSClose/tGSClose_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/googleStorageConnection.javajet
Labels: Need review, needs review

#5545 fix(TDI-45224): Review and update tJasper* dependencies.
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
Labels: Need review

#5573 fix(TDI-45224): Backport 7.4.1 - Review and update tJasper* dependencies.
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
Labels: Need review, backport

#5501 fix(TDI-45162): Rearrange imports in tELTPostgresql* and tELTTeradata components.
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataMap/tELTTeradataMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_java.xml
Labels: Need review

#5581 fix(TDI-45162): Backport 7.4.1 - Rearrange imports in tELTPostgresql* and tELTTeradata components.
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataMap/tELTTeradataMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_java.xml
Labels: Need review, backport
