Repository Talend/tdi-studio-se, pull requests merged in 2020-03, with the labels that each got.

#4502 Set logger level in org.talend.designer.codegen
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
Labels: Need review

#4458 fix(TUP-23956)createTable should not use Redshiftsso connection
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
Labels: Build running

#4516 fix(TUP-26193):Can`t find the connection by the key.
  main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ComponentRefController.java
Labels: Build running

#4512 Fix(TDI-31017): Added short UUID in filename pattern.
  main/plugins/org.talend.designer.components.localprovider/components/tPOP/tPOP_java.xml
Labels: Need review

#4511 bugfix(TUP-26117):Vertica: Db Version should be xxx(Deprecated) after
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTVerticaMap/tELTVerticaMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaConnection/tVerticaConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaInput/tVerticaInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutputBulkExec/tVerticaOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaRow/tVerticaRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaSCD/tVerticaSCD_java.xml
Labels: Build running

#4525 fix(TCOMP-1677): correct configuration value for non String context item
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
Labels: Need review

#4377 Mbasiuk/tdi 32442 dynamic excel dateformat
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#4531 bugfix(TUP-24728):Date and Time is not displaying when the Preferred …
  main/plugins/org.talend.designer.runprocess/src/main/java/messages.properties
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessContext.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/DebugProcessTosComposite.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/ui/ProcessComposite.java
Labels: buildme

#4537 fix(TUP-26285):Exchange Notify me when updated extensions are available
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
Labels: Build running

#4528 fix(TDI-43851): hide csvSchema in metadata editor
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/SettingVisitor.java
Labels: Need review

#4532 Fix(TDI-30526): Fix logger message for listed DB .
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/LogUtil.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForOutput.javajet
Labels: Need review

#4522 feat(TDI-43218): Extract token-retrieve to the utils lib
  main/plugins/org.talend.designer.components.libs/libs_src/azure-utils/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/azure-utils/src/main/java/org/talend/components/azure/runtime/token/AzureActiveDirectoryTokenGetter.java
Labels: Need review

#4530 fix(TUP-26231)Relative path not working in Talend v721
  main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/CodeGenerator.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/runprocess/Processor.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/ManageResourcePanel.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/service/ResourcesDependenciesService.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtil.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/dependencies/util/ResourceDependenciesUtilTest.java
Labels: Build running

#4551 fix column names are same
  main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/FOXUI.java
Labels: Build running

#4546 fix(TUP-26482):[Studio] Studio is very slow to build the job(the performance issue)
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/Expression.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/model/components/ExpressionTest.java
Labels: Build running

#4520 feat(TDI-43754): upgrade AWS SDK.
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRListInstances/tAmazonEMRListInstances_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRResize/tAmazonEMRResize_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/tSQSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageChangeVisibility/tSQSMessageChangeVisibility_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageDelete/tSQSMessageDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueCreate/tSQSQueueCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueDelete/tSQSQueueDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueList/tSQSQueueList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueuePurge/tSQSQueuePurge_java.xml
Labels: Build running, Need review

#4545 fix(TDI-32442): add missing else block
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
Labels: Need review

#4544 fix(TDI-43797): Update talend-mscrm library version
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
  main/plugins/org.talend.libraries.crm/pom.xml
Labels: Need review

#4555 Revert "Hwang/tup 26388"
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/statsandlogs/StatsAndLogsManager.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JobSettingUtil.java
Labels: Build running

#4567 fix column names are same (#4551)
  main/plugins/org.talend.designer.fileoutputxml/src/main/java/org/talend/designer/fileoutputxml/ui/FOXUI.java
Labels: Build running

#4561 fix(TUP-25963)Spark jobs - LOG4J_RUN_LEVEL not available in item
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
Labels: Build running

#4560 fix(TUP-26580):DI job with Big Data components fail when using the custom hadoop conf file location feature.
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
Labels: Build running

#4508 feat(TUP-16546)Prompt users for new password in Studio Connection when
  main/plugins/org.talend.repository/src/main/java/messages.properties
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/AbstractLoginActionPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionsDialog.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionsListComposite.java
Labels: Build running

#4568 fix(TDI-43919):update the new icons for tAzureSynapseXXX
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseClose/tAzureSynapseClose_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseCommit/tAzureSynapseCommit_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRollback/tAzureSynapseRollback_icon32.png
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_icon32.png
Labels: Need review
