Repository Talend/tdi-studio-se, pull requests merged in 2020-12, with the labels that each got.

#5579 fix(TUP-29090):improve since broken some junits .
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
Labels: Build running

#5588 fix(TUP-29366):[bug] studio can rename alias to an existing name.
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/AliasDialog.java
Labels: Build running

#5566 fix(TDI-45006): Hide "LIKE" operator from CRM-2016 On-Premise setup.
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
Labels: Need review

#5605 fix(TDI-45006): BP_741: Hide "LIKE" operator CRM-2016 and CRM-2018.
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
Labels: Need review, backport

#5584 fix(TDI-45135): Reuse same outputStream when 2 outputDelimited writin…
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_end.javajet
Labels: Need review

#5615 fix(TDI-45135): Reuse same outputStream when 2 outputDelimited writin…
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_end.javajet
Labels: Need review, backport

#5623 Rlecomte/tdi 45147 t gs copy src path issue
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_messages.properties
Labels: backport

#5617 feat(TUP-25346):tELTTeradataOutput - aliases are mandatory for calculated columns.
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_main.javajet
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/EParameterName.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
  main/plugins/org.talend.designer.dbmap/icons/property.png
  main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/oracle/OracleGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/UIManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/PropertySetDialog.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/image/ImageInfo.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarOutputZone.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/zone/toolbar/ToolbarZone.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTestHelper.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mysql/MysqlGenerationManagerTest.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/teradata/TeradataGenerationManagerTest.java
Labels: Build running

#5590 fix(TDI-45260): fix cr issue, improve crlf row separator performance
  main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend_file_enhanced/src/main/java/org/talend/fileprocess/delimited/RowParser.java
Labels: Need review

#5643 fix(TDI-45260): update components with new library version (#5602)
  main/plugins/org.talend.designer.components.localprovider/components/tApacheLogInput/tApacheLogInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tExtractPositionalFields/tExtractPositionalFields_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputFullRow/tFileInputFullRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSDelimited/tFileInputMSDelimited_java.xml.tmp
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMSPositional/tFileInputMSPositional_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputRegex/tFileInputRegex_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFixedFlowInput/tFixedFlowInput_java.xml
  main/plugins/org.talend.libraries.custom/.classpath
  main/plugins/org.talend.libraries.custom/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.custom/pom.xml
Labels: backport

#5520 fix(TDI-45124): enable transfer mode for ftps type
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
Labels: Need review

#5646 fix(TDI-45124): enable transfer mode for ftps type (#5520)
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
Labels: backport

#5637 fix(TUP-29072):improve for When renaming link (table) between teltinput and teltmap , the generated SQL query is not updated.
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommand.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTDefaultNameMigrationTask.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommandTest.java
Labels: Build running

#5638 fix(TUP-29072):improve for When renaming link (table) between teltinput and teltmap , the generated SQL query is not updated.
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommand.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/SpecialUpdateELTDefaultNameMigrationTask.java
  test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/ui/editor/cmd/ChangeConnTextCommandTest.java
Labels: Build running

#5642 fix(TDI-45366): fix for CVE issue with Apache Axis library.
  main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMInput/tVtigerCRMInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMOutput/tVtigerCRMOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
Labels: Need review

#5665 fix(TDI-45366): BP_741: fix for CVE issue with Apache Axis library. (#5642)
  main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMInput/tVtigerCRMInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVtigerCRMOutput/tVtigerCRMOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tWebServiceInput/tWebServiceInput_java.xml
Labels: Need review, backport

#5649 fix(TDI-45385): fix CVE for tBonita* components.
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: Need review

#5673 fix(TDI-45385): BP_741: fix CVE for tBonita* components.
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: Need review, backport

#5689 fix(TDI-45362):update talend-mscrm in crm libraries plugin
  main/plugins/org.talend.libraries.crm/pom.xml
Labels: Need review
