Repository Talend/tdi-studio-se, pull requests merged in 2020-08, with the labels that each got.

#5030 chore(TDI-44551): rename parameter
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_messages.properties
Labels: Need review

#5035 fix(TDI-44658): rearrange parameters in UI for BigQueryBulkExec
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
Labels: Need review

#5025 try fix junit to download jar
  test/plugins/org.talend.repository.test/src/org/talend/repository/handler/BuildJobHandlerTest.java
Labels: Build running

#5032 Fix: TUP-28040 Importing project from 7.1.1 to 7.3.1 with Context group is missing the variables.
  main/plugins/org.talend.repository/src/main/java/messages.properties
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/actions/importproject/ImportProjectBean.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/AbsAfterImportProjectAction.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/utils/AfterImportProjectUtil.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/ImportProjectAsWizard.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/newproject/copyfromeclipse/TalendWizardProjectsImportPage.java
Labels: Build running

#5055 fix(TUP-27374): Fix test case
  test/plugins/org.talend.designer.runprocess.test/src/org/talend/designer/runprocess/utils/JobVMArgumentsUtilTest.java
Labels: Build running

#5063 fix(TDI-44658): rearrange parameters in UI for BigQueryBulkExec (#5035)
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
Labels: Need review

#5076 tS3Connection setPathStyleAccess for better MinIO support (#5012)
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_messages.properties
Labels: backport

#5077 Hengzhao/backport73/tup 25103 (#5033)
  main/plugins/org.talend.designer.core/META-INF/MANIFEST.MF
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/viewer/proposal/TalendCompletionProposalComputer.java
  main/plugins/org.talend.designer.dbmap/META-INF/MANIFEST.MF
  main/plugins/org.talend.designer.dbmap/src/main/java/messages.properties
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/EltExpressionComposite.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/ExpressionBuilderDialogForElt.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/dialog/ExpressionComposite.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/proposal/expression/ExpressionProposalProvider.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/DataMapTableView.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/visualmap/table/OutputDataMapTableView.java
Labels: Build running

#5022 feat(TUP-27862)Add possibility to customize pattern for dates when (#…
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaController.java
Labels: Build running

#5122 fix(TDI-44063): update xercesImpl dependency (#5004)
  main/plugins/org.talend.designer.components.libs/libs_src/soap/pom.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputXML/tFileInputXML_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRSSInput/tRSSInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSOAP/tSOAP_java.xml
  main/plugins/org.talend.designer.components.localprovider/pom.xml
Labels: Need review, backport

#5102 fix(TESB-29963) MQ Dependency issues in Runtime
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
Labels: Build running

#5155 fix(TDI-44074): Fix performance for date mssql (#4638)
  main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
Labels: backport
