Repository Talend/tdi-studio-se, pull requests merged in 2020-02, with the labels that each got.

#4385 Fix TUP-25786 Enable online help (Remove temporary hard code version)
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
Labels: Build running

#4333 feat(TDI-43487): Update snowflake-jdbc for tCreateTable
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
Labels: Need review

#4381 fix(TDI-43231): change logging order
  main/plugins/org.talend.designer.components.localprovider/components/tELTTeradataOutput/tELTTeradataOutput_main.javajet
Labels: Need review

#4410 fix(TUP-25856):Error msg show under error log list when try to check couchbase help doc
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/AbstractTalendEditor.java
Labels: Build running

#4389 fix(TDI-43611): include all columns to reject row
  main/plugins/org.talend.designer.components.localprovider/components/tXSDValidator/tXSDValidator_main.javajet
Labels: Need review

#4309 fix(TUP-25378)Wrong settings in CDC Oracle component / wizard
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
Labels: Build running

#4417 fix(TUP-26023):Studio should open online help based on language
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/ComponentsHelpUtil.java
Labels: Build running

#4390 fix(TDI-32471): Remove unused mysql4 code
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_messages.properties
Labels: Need review

#4380 fix(TDI-43484): tSetDynamicSchema can't work with tFile***Positional
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputPositional/tFileInputPositional_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputPositional/tFileOutputPositional_begin.javajet
Labels: Need review

#4363 feat(TDI-40852): add dynamic support for tMSSQLBulkExec
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForBulk.javajet
Labels: Need review

#3282 fix(TDI-33414): change tMomInput backout behavior
  main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_end.javajet
Labels: Need review

#4428 feat(TDI-43510):Upgrade mysql driver for tCreateTable/tELTMysqlMap
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMysqlMap/tELTMysqlMap_java.xml
Labels: Need review

#4366 fix(TBD-9884) : Missing log42 conf on Yarn side
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/DefaultRunProcessService.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/RunProcessService.java
Labels: needs review

#4440 kjwang/Fix TUP-25777 Interger values are read as string after applying TPS-3637 (Fix failed tuj)
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
Labels: Build running

#4476 fix(TDI-43711): make CODEPAGE optional
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_messages_en.properties
Labels: Need review

#4463 Dsylaiev/tdi 43605 fix using existing connection with rest tcompv0
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplate/tSQLTemplate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateAggregate/tSQLTemplateAggregate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateCommit/tSQLTemplateCommit_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateFilterColumns/tSQLTemplateFilterColumns_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateFilterRows/tSQLTemplateFilterRows_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateMerge/tSQLTemplateMerge_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLTemplateRollback/tSQLTemplateRollback_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSalesforceEinsteinBulkExec/tSalesforceEinsteinBulkExec_main.javajet
Labels: Need review

#4493 Dgrygorenko/tdi 43480
  main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/src/main/java/org/talend/job/audit/JobEventAuditLoggerFactory.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/src/test/java/org/talend/job/audit/JobAuditLoggerTest.java
Labels: Need review
