Repository Talend/tdi-studio-se, pull requests merged in 2020-04, with the labels that each got.

#3215 fix(TDI-37349): Join thread in the finally block
  main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tWriteXMLFieldOut/tWriteXMLFieldOut_finally.javajet
Labels: Reviewing

#4578 Hengzhao/bugfix/tup 26476 t elt map group by in where clause2
  main/plugins/org.talend.designer.dbmap/META-INF/MANIFEST.MF
  main/plugins/org.talend.designer.dbmap/model/dbmap.ecore
  main/plugins/org.talend.designer.dbmap/model/dbmap.genmodel
  main/plugins/org.talend.designer.dbmap/plugin.xml
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/AbstractDBDataMapTable.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DBMapData.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DBMapperTableEntry.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DbmapFactory.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/DbmapPackage.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/FilterEntry.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/InputTable.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/OutputTable.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/AbstaceDBInOutTableImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/AbstractDBDataMapTableImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DBMapDataImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DBMapperTableEntryImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DbmapFactoryImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/DbmapPackageImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/FilterEntryImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/InputTableImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/OutputTableImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/VarTableImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/util/DbmapResourceFactoryImpl.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/util/DbmapSwitch.java
Labels: Build running

#4585 fix(TUP-26388)Amazon Redshift Driver class not working with Implicit
  main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/service/GenericService.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentManager.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentParameter.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleComponentParameterValue.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/components/MultipleGenricComponentManager.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobContextLoadComponent.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
Labels: Build running

#4603 TUP-26388 fix SQL script's syntax issue
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
Labels: Build running

#4604 TUP-26388 fix SQL script's syntax issue (#4603)
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/jobsettings/JobSettingsManager.java
Labels: buildme

#4609 Tup-26476 fix missing filterKind issue
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/model/emf/dbmap/impl/FilterEntryImpl.java
Labels: Build running

#4601 fix(TUP-26679):tMap editor was freezed
  main/plugins/org.talend.designer.mapper/src/main/java/org/talend/designer/mapper/ui/visualmap/table/InputDataMapTableView.java
Labels: Build running

#4582 bugfix(TUP-26439):Need to fix other rename components Migration task
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameELTJDBCComponentsMigrationTask.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameSQLDWHMigrationTask.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameSalesforceWaveMigrationTask.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameTCOMPCouchbaseMigrationTask.java
Labels: Build running

#4598 fix(TDI-43707): Remove mysql4 i18n labels
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlRow/tAmazonMysqlRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTMysqlMap/tELTMysqlMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlBulkExec/tMysqlBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlConnection/tMysqlConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlInput/tMysqlInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutputBulkExec/tMysqlOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlRow/tMysqlRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlSCD/tMysqlSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlSCDELT/tMysqlSCDELT_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlSP/tMysqlSP_messages.properties
Labels: Need review

#4584 Dsylaiev/tdi 39575 active directory for mssql
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutputBulkExec/tMSSqlOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutputBulkExec/tMSSqlOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/tMSSql/_tMSSqlConnection.javajet
Labels: Need review

#4513 Fix(TDI-31598): Don't add "connection" into globalMap for all dbConnection components - always duplicate.
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Connection/tAS400Connection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlConnection/tAmazonMysqlConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleConnection/tAmazonOracleConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tDB2Connection/tDB2Connection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tEXAConnection/tEXAConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFirebirdConnection/tFirebirdConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInformixConnection/tInformixConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tIngresConnection/tIngresConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInterbaseConnection/tInterbaseConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlConnection/tMysqlConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaConnection/tNetezzaConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleConnection/tOracleConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelConnection/tParAccelConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusConnection/tPostgresPlusConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlConnection/tPostgresqlConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLiteConnection/tSQLiteConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseConnection/tSybaseConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataConnection/tTeradataConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseConnection/tVectorWiseConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaConnection/tVerticaConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/HelpClass/HelpClass.javajet
Labels: Need review

#4521 CreateTable component should use given connection
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/PropertyChangeCommand.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/TalendEditorDropTargetListener.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/PropertyTypeController.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/RepositoryReviewDialog.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/processor/RepositoryTypeProcessor.java
Labels: Build running

#4622 Dsylaiev/tdi 43931 pass full date to independand child job
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: Need review

#4627 bugfix(TUP-26796):Error "Can't find filed of null" show in error log
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/process/Process.java
Labels: Build running

#4617 feat(TCOMP-1681): manage tacokit components in OSGi/Microservice job export
  main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_job_template.xml
  main/plugins/org.talend.designer.maven.job/resources/templates/osgi/assembly_route_template.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JavaScriptForESBWithMavenManager.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/wizards/exportjob/scriptsmanager/esb/JobJavaScriptOSGIForESBManager.java
  main/plugins/org.talend.sdk.component.studio-integration/plugin.xml
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/provider/TacokitExportDependenciesProvider.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitDependencyService.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
Labels: Build running

#4634 fix(TUP-26639):Talend Cloud studio Issues - Group context and
  main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/service/GenericDBService.java
  main/plugins/org.talend.repository.generic/src/main/java/org/talend/repository/generic/util/GenericContextUtil.java
  test/plugins/org.talend.repository.generic.test/src/main/java/org/talend/repository/generic/util/GenericContextUtilTest.java
Labels: Build running

#4484 feat(TDI-37016): Add dynamic support for tVerticaBulkExec
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaBulkExec/tVerticaBulkExec_messages_en.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForBulk.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/createTableFromDynamicInBulkExec.javajet
Labels: Need review

#4547 feat(TDI-43756):extends STS AssumeRole fields for S3.
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRListInstances/tAmazonEMRListInstances_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRListInstances/tAmazonEMRListInstances_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRManage/tAmazonEMRManage_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRResize/tAmazonEMRResize_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonEMRResize/tAmazonEMRResize_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonRedshiftManage/tAmazonRedshiftManage_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulk/tRedshiftOutputBulk_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/SQSClient.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/tSQSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSConnection/tSQSConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSInput/tSQSInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageChangeVisibility/tSQSMessageChangeVisibility_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageChangeVisibility/tSQSMessageChangeVisibility_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageDelete/tSQSMessageDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSMessageDelete/tSQSMessageDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueAttributes/tSQSQueueAttributes_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueCreate/tSQSQueueCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueCreate/tSQSQueueCreate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueDelete/tSQSQueueDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueDelete/tSQSQueueDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueList/tSQSQueueList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueueList/tSQSQueueList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueuePurge/tSQSQueuePurge_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSQueuePurge/tSQSQueuePurge_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/Amazon/CredentialsProvider.javajet
Labels: Build running, Need review

#4641 fix(TUP-26683): Inputs label in documentation not the same as FlowDiagram
  main/plugins/org.talend.designer.documentation/src/org/talend/designer/documentation/generation/HTMLDocGenerator.java
Labels: Build running

#4632 fix(TUP-26939:Tmap shows null values when using Expression Builder.
  main/plugins/org.talend.expressionbuilder/src/main/java/org/talend/expressionbuilder/test/shadow/VirtualRowGeneratorNode.java
Labels: Build running
