Repository Talend/tdi-studio-se, pull requests merged in 2020-09, with the labels that each got.

#5150 feat(TDI-44730): snowflake driver
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
Labels: Need review

#5133 fix(TDI-44748):Error in method "add" for the component tFileOutputMSXML
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
Labels: Need review

#5158 fix(TDI-44748):Error in method "add" for the component tFileOutputMSXML
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputMSXML/tFileOutputMSXML_begin.inc.javajet
Labels: Need review

#5156 fix(TDI-44743): backport to "master" branch
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review, backport

#5132 TalendExcel: read password protected files.
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5160 fix(TDI-30522): extra '(' removed.
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
Labels: Need review

#5161 fix(TDI-30522): extra '(' removed
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
Labels: Need review

#5125 fix(TUP-28258):tETLInput and tETLMap does not show datatypes for Snowflake DB on Import Metadata。
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/RepositoryChangeMetadataCommand.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/managers/MapperManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/ui/MapperUI.java
Labels: Build running

#5113 fix(TDI-44394): Fix migration tcomp for javajet
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/CheckAzureBlobStorageKeepRemoteDirJavajetToTCOMPv0.java
Labels: Need review

#5210 feat(TUP-23827): Runtime Lineage
  main/plugins/org.talend.designer.codegen/jet_stub/component_part_footer.javajet
  main/plugins/org.talend.designer.codegen/jet_stub/component_part_header.javajet
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.codegen/jet_stub/header.javajet
  main/plugins/org.talend.designer.codegen/jet_stub/tacokit_runtime_log.javajet
  main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/src/main/java/org/talend/job/audit/JobAuditLogger.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-job-monitoring/src/main/java/org/talend/job/audit/JobContextBuilder.java
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
  main/plugins/org.talend.designer.core/plugin.properties
  main/plugins/org.talend.designer.core/plugin.xml
  main/plugins/org.talend.designer.core/src/main/java/messages.properties
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/model/process/DataProcess.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/RuntimeLineagePageTester.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/projectsetting/RuntimeLineageTreeViewPage.java
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
  test/plugins/org.talend.designer.core.test/src/core/model/components/NodeUtilTest.java
Labels: Build running

#5001 fix(TDI-44568): Update TalendExcel library.
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
Labels: Need review

#5040 fix(TDI-44568): Update talendMsgMailUtil library
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java
Labels: Need review

#5041 fix(TDI-44568): Update simpleexcel library
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
Labels: Need review

#5042 fix(TDI-44568): Update org.talend.libraries.excel plugin
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.excel/build.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5043 fix(TDI-44568): Update Apache POI version in components
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
Labels: Need review

#5250 Revert "fix(TDI-44568): Update Apache POI version in components"
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
Labels: Need review

#5251 Revert "fix(TDI-44568): Update org.talend.libraries.excel plugin"
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.excel/build.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5252 Revert "fix(TDI-44568): Update simpleexcel library"
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
Labels: Need review

#5253 Revert "fix(TDI-44568): Update talendMsgMailUtil library"
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java
Labels: Need review

#5254 Revert "fix(TDI-44568): Update TalendExcel library."
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
Labels: Need review

#5173 fix(TESB-30136) exclude the jakarta.activation
  main/plugins/org.talend.repository/resources/osgi-exclude.properties
Labels: Build running

#5269 fix(TDI-44568): Cumulative changes for POI update task (all-in-one)
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DataBufferCache.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/EnoughDataException.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendMsgMailUtil/src/main/java/org/talend/msg/utils/MsgMailUtil.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutput/tJasperOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tJasperOutputExec/tJasperOutputExec_java.xml
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.excel/build.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5208 fix(TDI-44771): Fix error code for prejob in multithread run
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
Labels: Need review

#5285 fix(TDI-44771): Fix error code for prejob in multithread run (#5208)
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
Labels: Need review, backport

#5216 fix(TDI-44883): set value of ERROR_MESSAGE in tFileInputJSON component
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/xpath.javajet
Labels: Need review

#5290 fix(TDI-44883): set value of ERROR_MESSAGE
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/jsonpath_javascript_api.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputJSON/xpath.javajet
Labels: Need review, backport

#5265 chore: TDI-32442 revert
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/DefaultTalendSheetContentsHandler.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/ExcelReader.java
  main/plugins/org.talend.designer.components.libs/libs_src/simpleexcel/src/main/java/com/talend/excel/xssf/event/TalendXSSFSheetXMLHandler.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.libraries.excel/.classpath
  main/plugins/org.talend.libraries.excel/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review
