Repository Talend/tdi-studio-se, pull requests merged in 2020-06, with the labels that each got.

#4649 bugfix(TUP-25171):Issue when using components inside Joblet
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/cmd/NodesPasteCommand.java
Labels: Build running

#4761 fix(TDI-30505): Backport fix from "master"
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tEXAOutput/tEXAOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tHSQLDbOutput/tHSQLDbOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInformixOutput/tInformixOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tIngresOutput/tIngresOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInterbaseOutput/tInterbaseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMaxDBOutput/tMaxDBOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaOutput/tNetezzaOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelOutput/tParAccelOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLiteOutput/tSQLiteOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataOutput/tTeradataOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseOutput/tVectorWiseOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/DBOutputEndGlobalVars.javajet
Labels: Need review, backport

#4734 Tup-27070
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_main.javajet
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/DbMapComponent.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/mssql/MssqlGenerationManager.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
Labels: Build running

#4772 TUP-27070 fix cross join cases
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/mssql/MssqlGenerationManagerTest.java
Labels: Build running

#4775 feat(TUP-27259)Change default driver to Microsoft official for MSSql
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeMSSQLDBDefaultVersionMigrationTask.java
Labels: Build running

#4737 feat(TDI-44109): Use ftps library for FTP mode
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPClose/tFTPClose_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPClose/tFTPClose_finally.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/commons_net_create_connection.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftp_connect.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftps_connect.javajet
Labels: Need review

#4788 Hengzhao/tup 27408
  main/plugins/org.talend.designer.core.generic/src/main/java/messages.properties
  main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/controller/ButtonController.java
Labels: Build running

#4809 fix(TDI-44165) add null marker field
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_messages.properties
Labels: Need review

#2534 tFileInputMail_MIME.javajet : avoid a java.lang.NullPointerException
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Labels: Need review

#4843 fix(TDI-44355): Updated CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: Need review

#4844 fix(TDI-44355): Backport to 'maintenance/7.3' branch
  CONTRIBUTORS.md
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputMail/tFileInputMail_MIME.javajet
Labels: Need review, backport

#4834 Dsylaiev/tdi 44109 reintegrate feature for 7.3
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPClose/tFTPClose_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPClose/tFTPClose_finally.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/commons_net_create_connection.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftp_connect.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftps_connect.javajet
Labels: Need review

#4599 Fix(TDI-44021): Replaced join(10000) with join();
  main/plugins/org.talend.designer.components.localprovider/components/tGPGDecrypt/tGPGDecrypt_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSystem/tSystem_begin.javajet
Labels: Need review

#4768 Mbasiuk/tdi 44165 add null marker field
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryOutputBulk/tBigQueryOutputBulk_messages.properties
Labels: Need review

#4841 fix(TUP-27607)Metadata Database connection with special characters(double quote) in the password
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/AbstractElementPropertySectionController.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/properties/controllers/GuessSchemaProcess.java
Labels: Build running

#4873 fix(TDI-44412): Implemented optional component fail when no files found by mask.
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet
Labels: Need review, backport

#4858 fix(TDI-44412): Implemented optional component fail when no files found by mask.
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_main.javajet
Labels: Need review
