Repository Talend/tdi-studio-se, pull requests merged in 2021-01, with the labels that each got.

#5707 fix(TDI-45440): fix CVE for Hibernate-Core-3.6.10
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: Need review

#5721 fix(TDI-45440): BP_741: fix CVE for Hibernate-Core-3.6.10 (#5707)
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: Need review, backport

#5709 feat(TDI-45007 & TDI-31602): Enhance component tGreenplumGPLoad
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
Labels: Need review

#5716 feat(TDI-45144): Support For GreenPlum 6.x
  main/plugins/org.talend.designer.components.localprovider/components/tELTGreenplumMap/tELTGreenplumMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTGreenplumMap/tELTGreenplumMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumBulkExec/tGreenplumBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumBulkExec/tGreenplumBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumInput/tGreenplumInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumInput/tGreenplumInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutputBulkExec/tGreenplumOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutputBulkExec/tGreenplumOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumRow/tGreenplumRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumRow/tGreenplumRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_java.xml
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeDefaultDriver4GreenplumMigrationTask.java
Labels: Need review

#5727 feat(TDI-45144): Support For GreenPlum 6.x (#5716)
  main/plugins/org.talend.designer.components.localprovider/components/tELTGreenplumMap/tELTGreenplumMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTGreenplumMap/tELTGreenplumMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumBulkExec/tGreenplumBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumBulkExec/tGreenplumBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumConnection/tGreenplumConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumInput/tGreenplumInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumInput/tGreenplumInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutputBulkExec/tGreenplumOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutputBulkExec/tGreenplumOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumRow/tGreenplumRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumRow/tGreenplumRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumSCD/tGreenplumSCD_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlBulkExec/tPostgresqlBulkExec_java.xml
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeDefaultDriver4GreenplumMigrationTask.java
Labels: Need review

#5737 feat(TDI-45007 & TDI-31602): Enhance component tGreenplumGPLoad (#5709)
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_messages.properties
Labels: Need review

#5746 fix(TDI-45513):tGreenplumGPLoad global variable "RUNTIME" should be Long type
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
Labels: Need review

#5729 fix(TDI-45455): excel output exceeding characters
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendExcel/src/main/java/org/talend/ExcelTool.java
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_messages.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5730 fix(TDI-45455): excel output exceeding characters
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_messages.properties
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review

#5750 fix(TDI-45513):tGreenplumGPLoad global variable "RUNTIME" should be Long type(#5746)
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumGPLoad/tGreenplumGPLoad_java.xml
Labels: Need review

#5770 fix(TDI-45400):Dynamic Schema has default length of 100 even after setting to different amount
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeFileInputDynamicFieldLength.java
Labels: Need review

#5785 fix(TDI-45400):Dynamic Schema has default length of 100 even after setting to different amount (#5770)
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputDelimited/tFileInputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeFileInputDynamicFieldLength.java
Labels: Need review

#5752 fix(TUP-30108):tELTMSSqlInput & tELTMSSqlMap context not recognized after migrating to 7.3.1.
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/language/generation/DbGenerationManager.java
  main/plugins/org.talend.designer.dbmap/src/main/java/org/talend/designer/dbmap/utils/DBMapHelper.java
  test/plugins/org.talend.designer.dbmap.test/src/org/talend/designer/dbmap/language/generation/DbGenerationManagerTest.java
Labels: Build running

#5753 fix(TDI-30267): adjusting batch insert logic for Oracle DB.
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet
Labels: Need review
