Repository Talend/tdi-studio-se, pull requests merged in 2021-05, with the labels that each got.

#6102 fix(TDI-45642): Fix codegen error for Greenplum
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
Labels: Need review

#6173 fix(TDI-45642): Fix codegen error for Greenplum (#6102)
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
Labels: backport

#6018 feat(TDI-45836): Standalone connectors support
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_end.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_finally.javajet
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/enums/ETaCoKitComponentType.java
Labels: Need review, Work in progress

#6178 fix(TDI-46004): tEXist components and tXMLRPCInput dependency import.
  main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
Labels: Need review

#6197 fix(TDI-46004): tEXist components and tXMLRPCInput dependency import.
  main/plugins/org.talend.designer.components.localprovider/components/tEXistConnection/tEXistConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistDelete/tEXistDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistGet/tEXistGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistList/tEXistList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistPut/tEXistPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXQuery/tEXistXQuery_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tEXistXUpdate/tEXistXUpdate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tXMLRPCInput/tXMLRPCInput_java.xml
Labels: Need review, backport

#6137 fix(TDI-45824): Bump jersey for tRest
  main/plugins/org.talend.designer.components.localprovider/components/tREST/tREST_java.xml
Labels: Need review

#6225 fix(TDI-45910):Jakarta-ORO imported (#6166)
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
Labels: backport

#6219 fix(TDI-46060): Fix compile error for tFTPFileList
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Labels: Need review

#6231 fix(TDI-46060): Fix compile error for tFTPFileList (#6219)
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Labels: Need review, backport

#6230 fix(TDI-46060): Fix compile error for tFTPFileList (#6219)
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
Labels: backport

#6268 feat(TDI-45963): after variables (#5933)
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_end.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_process_records_end.javajet
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
Labels: backport

#6253 fix(TDI-46100): connection support
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/standalone/standalone_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
Labels: Need review
