Repository Talend/tdi-studio-se, pull requests merged in 2021-09, with the labels that each got.

#6576 fix(TDI-46610): Add missing logout before disconnect FTPS FTPGet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
Labels: Need review

#6636 fix(TDI-46315):add migration task for changing the value of one dbversion item (#6606)
  main/plugins/org.talend.designer.runprocess/src/main/java/org/talend/designer/runprocess/java/JavaProcessor.java
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeDBVersion4tSAPConnection.java
Labels: Need review

#6626 fix(TDI-46612): add ERROR_MESSAGE to the DBRow components.
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
Labels: Need review

#6639 fix(TDI-46612): BP_801 - add ERROR_MESSAGE to the DBRow components.
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/AbstractDBRowMain.javajet
Labels: Need review, backport

#6602 fix(TDI-46511):[7.3.1] tMomInput: "Sleeping time" parameter is not used in code generated for Websphere MQ
  main/plugins/org.talend.designer.components.localprovider/components/tMomInput/tMomInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
Labels: Need review

#6644 fix(TDI-46511):[7.3.1] tMomInput: "Sleeping time" parameter is not used in code generated for Websphere MQ (#6602)
  main/plugins/org.talend.designer.components.localprovider/components/tMomInput/tMomInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMomInputLoop/tMomInputLoop_java.xml
Labels: Need review

#6627 fix(TDI-46527):Dataloss with Parquet components for timestamp field with nano seconds
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/src/main/java/org/talend/parquet/utils/NanoTimeUtils.java
Labels: Need review

#6651 fix(TDI-46315):migration task should return ExecutionResult.NOTHING_TO_DO when doesn't change anything
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeDBVersion4tSAPConnection.java
Labels: Need review

#6658 fix(TDI-46527):Dataloss with Parquet components for timestamp field with nano seconds(#6627)
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/src/main/java/org/talend/parquet/utils/NanoTimeUtils.java
Labels: Need review

#6679 TDI-46772 - Port TDI-46610 to master
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_end.javajet
Labels: backport

#6684 fix(TDI-46614): BP_801: CVE - update "commons-compress" to 1.21
  main/plugins/org.talend.designer.components.libs/libs_src/checkArchive/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talendzip/pom.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileArchive/tFileArchive_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFileUnarchive/tFileUnarchive_java.xml
  main/plugins/org.talend.libraries.custom/pom.xml
Labels: Need review, backport
