Repository Talend/tdi-studio-se, pull requests merged in 2021-08, with the labels that each got.

#6477 feat(TDI-46423):tSQSOutput - Get Amazon SQS Response - "Message ID"
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_messages.properties
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameConnectionName4tSQSOutput.java
Labels: Need review

#6510 feat(TDI-46423):tSQSOutput - Get Amazon SQS Response - "Message ID" (#6477)
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQSOutput/tSQSOutput_messages.properties
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RenameConnectionName4tSQSOutput.java
Labels: Need review

#6488 fix(TDI-46496): Hide password property for sftp not pass auth
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
Labels: Need review

#6535 fix(TDI-46496): Hide password property for sftp not pass auth (#6488)
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
Labels: backport

#6561 chore(TDI-46270): improve logging for tFileList component.
  main/plugins/org.talend.designer.components.localprovider/components/tFileList/tFileList_begin.javajet
Labels: Need review

#6569 chore(TDI-46270): BP_801: improve logging for tFileList component.
  main/plugins/org.talend.designer.components.localprovider/components/tFileList/tFileList_begin.javajet
Labels: Need review, backport

#6579 fix(TDI-46587):tParquetOutput - DI Job - Dynamic Issue (#6570)
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/src/main/java/org/talend/parquet/utils/TalendParquetUtils.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-parquet/src/test/java/org/talend/parquet/util/TalendParquetUtilsTest.java
Labels: Need review

#6512 Dsylaiev/tdi-46535 add cyberark vault component wrapper
  main/plugins/org.talend.designer.components.libs/libs_src/cyberark-wrapper/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/cyberark-wrapper/src/main/java/org/talend/components/cyberark/CyberarkWrapperRuntime.java
  main/plugins/org.talend.designer.components.libs/libs_src/cyberark-wrapper/src/main/java/org/talend/components/cyberark/CyberarkWrapperUtils.java
  main/plugins/org.talend.designer.components.libs/libs_src/cyberark-wrapper/src/test/java/org/talend/components/cyberark/CyberarkWrapperRuntimeTest.java
  main/plugins/org.talend.designer.components.libs/libs_src/cyberark-wrapper/src/test/java/org/talend/components/cyberark/CyberarkWrapperUtilsTest.java
  main/plugins/org.talend.designer.components.libs/libs_src/cyberark-wrapper/src/test/resources/mockito-extensions/org.mockito.plugins.MockMake
Labels: Need review
