Repository Talend/tdi-studio-se, pull requests merged in 2021-12, with the labels that each got.

#6961 fix(TDI-47179): BP_801: enable batch checkbox for Postgres Upsert.
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
Labels: Need review

#6962 fix(TDI-47179): BP_731: enable batch checkbox for Postgres Upsert.
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
Labels: Need review

#6987 fix(TDI-47179): enable batch checkbox for Postgres Upsert.
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
Labels: Need review, backport

#6989 feat(TDI-45793):Add migration task for tSAPADSOInput
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ChangeConnectionType4tSAPADSOInput.java
Labels: Need review

#7002 fix(TDI-46834): Additional columns in tDBOutput doesn`t generate code properly for MySQL and Oracle
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet
Labels: backport

#6992 fix(TDI-46943): Dynamic schema fail's with Excel
  main/plugins/org.talend.designer.components.localprovider/components/tFileInputExcel/tFileInputExcel_begin.javajet
Labels: Need review, backport

#7019 Dsylaiev/tdi 46910 fix codegen with dynamics
  main/plugins/org.talend.designer.components.localprovider/components/templates/db_output_bulk.skeleton
Labels: Need review

#7042 fix(TDI-46743): BP_801: avoid file locking when using "streaming append" feature.
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputExcel/tFileOutputExcel_java.xml
  main/plugins/org.talend.libraries.excel/pom.xml
Labels: Need review, backport

#6998 fix(TDI-47228): tPostgresqlOutput Upsert existing connection
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
Labels: Need review

#7048 fix(TDI-47228): tPostgresqlOutput Upsert existing connection
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
Labels: Need review, backport

#7049 fix(TDI-47228): tPostgresqlOutput Upsert existing connection
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
Labels: Need review, backport

#6981 feat(TDI-46430): Kafka Input Output Avro support
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ApplySecurityAfterAdvancedKafkaProperties.java
Labels: Need review

#7067 feat(TDI-46430): Kafka Input Output Avro support (#6981)
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ApplySecurityAfterAdvancedKafkaProperties.java
Labels: Need review, backport
