Repository Talend/tdi-studio-se, pull requests merged in 2021-04, with the labels that each got.

#6017 fix(TDI-45776): Bump slf4j-jdk14 version to make it downloadable
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: Need review

#6043 fix(TDI-45776): Bump slf4j-jdk14 version to make it downloadable (#6017) BACKPORT
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaDeploy/tBonitaDeploy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tBonitaInstantiateProcess/tBonitaInstantiateProcess_java.xml
Labels: backport

#5908 fix(TDI-45650): [7.3.1] tDeltaLakeOutput- not handling the updates when we are using Dynamic schema
  main/plugins/org.talend.designer.codegen/jet_stub/generic/component_main.javajet
  main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/pom.xml
  main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer/IncomingSchemaEnforcer.java
  main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/test/java/org/talend/codegen/enforcer/IncomingSchemaEnforcerTest.java
  main/plugins/org.talend.designer.core.generic/src/main/java/org/talend/designer/core/generic/model/Component.java
  main/plugins/org.talend.libraries.custom/plugin.xml
  main/plugins/org.talend.libraries.custom/pom.xml
Labels: Build running

#5848 feat(TUP-30475): Test of lite studio
  main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/config/TalendJetEmitter.java
  main/plugins/org.talend.designer.codegen/src/main/java/org/talend/designer/codegen/model/CodeGeneratorEmittersPoolFactory.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/editor/TalendEditorPaletteFactory.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/ExchangePreferencePage.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PerformancePreferencePage.java
  main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/ui/preferences/PreferenceInitializer.java
  main/plugins/org.talend.repository.view.di/src/main/java/org/talend/repository/view/di/metadata/tester/DIMetadatasNodeTester.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/RepositoryService.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/CustomComponentProjectSettingPageTester.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/CustomComponentSettingPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/preference/ProjectRefSettingPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/dialog/ProjectSettingsPreferenceDialog.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginComposite.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginDialog.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginHelper.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/LoginProjectPage.java
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/ui/login/connections/ConnectionsListComposite.java
  main/plugins/org.talend.sdk.component.studio-integration/.classpath
  main/plugins/org.talend.sdk.component.studio-integration/META-INF/MANIFEST.MF
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/documentation/toc/TaCoKitTocProvider.java
Labels: Work in progress

#5971 fix(TDI-42478): tFTPConnection : SSL/TLS Client Authentication does n…
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftpsPrivateKeyManager.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftps_connect.javajet
Labels: Need review

#6057 fix(TDI-42478): tFTPConnection : SSL/TLS Client Authentication does n…
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftpsPrivateKeyManager.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/ftps_connect.javajet
Labels: Need review, backport

#6039 fix(TDI-45642): Count key columns
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateAndDelete.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateOnDuplicateKey.javajet
Labels: Need review

#6064 fix(TDI-45642): Count key columns (#6039)
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateAndDelete.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateOnDuplicateKey.javajet
Labels: Need review, backport

#6080 Rlecomte/tdi 45014 sftp double auth master
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPConnection/tFTPConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPDelete/tFTPDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileExist/tFTPFileExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileList/tFTPFileList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPFileProperties/tFTPFileProperties_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPPut/tFTPPut_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPRename/tFTPRename_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tFTPTruncate/tFTPTruncate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/FTP/sftp_connect.javajet
Labels: backport

#6099 Dsylaiev/tdi 45642 revert from april release
  main/plugins/org.talend.designer.components.localprovider/components/tAS400Output/tAS400Output_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAccessOutput/tAccessOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonMysqlOutput/tAmazonMysqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAmazonOracleOutput/tAmazonOracleOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tDB2Output/tDB2Output_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tExasolOutput/tExasolOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFirebirdOutput/tFirebirdOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tHSQLDbOutput/tHSQLDbOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInformixOutput/tInformixOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tIngresOutput/tIngresOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tInterbaseOutput/tInterbaseOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tJavaDBOutput/tJavaDBOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMaxDBOutput/tMaxDBOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tNetezzaOutput/tNetezzaOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tParAccelOutput/tParAccelOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresPlusOutput/tPostgresPlusOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSQLiteOutput/tSQLiteOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tSybaseOutput/tSybaseOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tTeradataOutput/tTeradataOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVectorWiseOutput/tVectorWiseOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tVerticaOutput/tVerticaOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateAndDelete.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Output/CheckKeysForUpdateOnDuplicateKey.javajet
Labels: revert

#6104 feat(TDI-45323): new auth provider web token (#6060)
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_messages.properties
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTask.java
Labels: backport

#6105 feat(TDI-45323): new auth provider web token
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketCreate/tS3BucketCreate_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketDelete/tS3BucketDelete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketExist/tS3BucketExist_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3BucketList/tS3BucketList_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/S3Client.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Connection/tS3Connection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Copy/tS3Copy_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Delete/tS3Delete_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Get/tS3Get_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3List/tS3List_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tS3Put/tS3Put_messages.properties
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/ReplaceInheritCredentialCheckBoxWithDropDownListTask.java
Labels: backport

#6100 Kjwang/fix tup 31145 tck guess schema m
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/close/close_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/close/close_end.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/close/close_finally.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/configuration.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/connection/connection_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/connection/connection_end.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/connection/connection_finally.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
  main/plugins/org.talend.sdk.component.studio-integration/messages.properties
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ComponentModel.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/Lookups.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/TaCoKitGenericProvider.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/VirtualComponentModel.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/TaCoKitCache.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/metadata/handler/TaCoKitDragAndDropHandler.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/AbstractActionParameter.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/action/SettingsActionParameter.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/AbstractConnectorCreator.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/ConnectorCreatorFactory.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/connector/VirtualComponentConnectorCreator.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/model/parameter/ElementParameterCreator.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/ComponentService.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/service/TaCoKitService.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/composite/TaCoKitComposite.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/ui/guessschema/TaCoKitGuessSchemaProcess.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitConst.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtil.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/util/TaCokitImageUtil.java
  main/plugins/org.talend.sdk.component.studio-integration/src/main/java/org/talend/sdk/component/studio/websocket/WebSocketClient.java
  test/plugins/org.talend.sdk.component.studio-integration.test/src/main/java/org/talend/sdk/component/studio/util/TaCoKitUtilTest.java
Labels: Build running

#6094 fix(TDI-43931) pass full date to independand child job
  main/plugins/org.talend.designer.codegen/jet_stub/footer.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRunJob/tRunJob_main.javajet
Labels: backport

#6076 fix(TDI-45879): save initial value of NB_LINE to globalMap.
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
Labels: Need review

#6155 fix(TDI-45879): BP_741: save initial value of NB_LINE to globalMap.
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/input/input_begin.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_begin_initialize.javajet
Labels: Need review, backport
