Repository Talend/tdi-studio-se, pull requests merged in 2021-11, with the labels that each got.

#6862 fix(TDI-46968): fix compile error for tGreenplumOutput.
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
Labels: Need review

#6863 fix(TDI-46968): fix compile error for tGreenplumOutput.
  main/plugins/org.talend.designer.components.localprovider/components/tGreenplumOutput/tGreenplumOutput_begin.javajet
Labels: Need review, backport

#6846 fix(TDI-46930): wrap filename
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_end.javajet
Labels: backport

#6707 fix(TDI-46746): CVE - update "protobuf-java" to 3.4.0
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryBulkExec/tBigQueryBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketCreate/tGSBucketCreate_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketDelete/tGSBucketDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketExist/tGSBucketExist_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSBucketList/tGSBucketList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSConnection/tGSConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSCopy/tGSCopy_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSDelete/tGSDelete_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSList/tGSList_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tGSPut/tGSPut_java.xml
Labels: Need review

#6706 fix(TDI-46790): Fix fetching big files GSGet
  main/plugins/org.talend.designer.components.localprovider/components/tGSGet/tGSGet_begin.javajet
Labels: Need review

#6825 fix(TDI-46834): Additional columns in tDBOutput doesn`t generate code properly
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet
Labels: Need review

#6868 fix(TDI-46834): Additional columns in tDBOutput doesn`t generate code properly
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tOracleOutput/tOracleOutput_main.javajet
Labels: Need review

#6811 chore(TDI-46752): CVE: Oauth 2.0 SDK with OpenID
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
Labels: Need review

#6891 chore(TDI-46752): CVE: Oauth 2.0 SDK with OpenID (#6811)
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
Labels: backport

#6916 fix(TDI-46912): tELTOutput cannot locate & drop existing table in Snowflake.
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForELT.javajet
Labels: Need review, backport

#6918 fix(TDI-46912): tELTOutput cannot locate & drop existing table in Snowflake.
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/_tableActionForELT.javajet
Labels: Need review, backport

#6878 feat(TDI-44717): tPostgresqlOutput Upsert feature
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_messages.properties
Labels: Need review

#6882 feat(TDI-44717): Postgres Upsert feature (backport to 8.0.1)
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_messages.properties
Labels: Need review, backport

#6919 feat(TDI-44717): BP_801: Postgres Upsert feature.
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_messages.properties
Labels: Need review, backport

#6920 fix(TDI-46986): tFTPGet component unable to get file from FileZilla Server, with a particular Filemask in Studio, after September patch, Patch_20210924_R2021-09_v2-7.3.1
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
Labels: Need review

#6927 feat(TDI-44717): fix backport issue for "master" branch.
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_main.javajet
Labels: Need review

#6928 feat(TDI-44717): fix backport issue for "maintenance/8.0" branch.
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_end.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tPostgresqlOutput/tPostgresqlOutput_main.javajet
Labels: Need review

#6930 fix(TDI-46930): wrap filename (#6846)
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputDelimited/tFileOutputDelimited_end.javajet
Labels: backport

#6935 chore(TDI-46752): CVE: Oauth 2.0 SDK with OpenID (#6811)
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseBulkExec/tAzureSynapseBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseConnection/tAzureSynapseConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseInput/tAzureSynapseInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseOutput/tAzureSynapseOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tAzureSynapseRow/tAzureSynapseRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlBulkExec/tMSSqlBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlConnection/tMSSqlConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlInput/tMSSqlInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlOutput/tMSSqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlRow/tMSSqlRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSCD/tMSSqlSCD_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMSSqlSP/tMSSqlSP_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
Labels: Need review, backport

#6921 fix(TDI-46791): tBigQueryInput - Component returning extra row of NULL values
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/BigQueryInputQueryHelper.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tBigQueryInput/tBigQueryInput_begin.javajet
Labels: Need review, backport

#6922 fix(TDI-46984): tFTPGet component unable to get file from FileZilla Server, with a particular Filemask in Studio, after September patch, Patch_20210924_R2021-09_v2-7.3.1
  main/plugins/org.talend.designer.components.localprovider/components/tFTPGet/tFTPGet_begin.javajet
Labels: Need review, backport
