Repository Talend/tdi-studio-se, pull requests merged in 2022-01, with the labels that each got.

#7104 fix(TDI-47222): invoke stop after flush (#6985)
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_end.javajet
  main/plugins/org.talend.sdk.component.studio-integration/jet_stub/generic/processor/processor_process_records_end.javajet
Labels: backport

#7108 feat(TDI-46151): Filter data based on return value in subquery in source database before pushing it down to a tDBInput to execute (#6906)
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlMap/tELTMSSqlMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTMSSqlOutput/tELTMSSqlOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTMap/tELTMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTMap/tELTMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleMap/tELTOracleMap_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleMap/tELTOracleMap_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tELTOutput/tELTOutput_messages.properties
Labels: Need review, backport

#7115 fix(TDI-47375):tMicrosoftCRM components with compile error when using OnPremise 2011
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmInput/tMicrosoftCrmInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tMicrosoftCrmOutput/tMicrosoftCrmOutput_java.xml
Labels: Need review
