Repository Talend/tdi-studio-se, pull requests merged in 2022-04, with the labels that each got.

#7351 fix(TDI-47725): increment "nb_line" counter in tMySQLOutput for "on duplicate" output action.
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
Labels: Need review

#7390 fix(TDI-47725): increment nb_line counter for "on duplicate" output action.
  main/plugins/org.talend.designer.components.localprovider/components/tMysqlOutput/tMysqlOutput_main.javajet
Labels: Need review, backport

#7360 fix(TDI-47133): the log "closing the connection" in tCreateTable is not right
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
Labels: Need review

#7359 fix(TDI-47133): the log "closing the connection" in tCreateTable is not right
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
Labels: backport

#7056 feat(TDI-47263): Upgrade Redshift driver to v2.x
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_main.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tCreateTable/tCreateTable_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftBulkExec/tRedshiftBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftConnection/tRedshiftConnection_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftInput/tRedshiftInput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutput/tRedshiftOutput_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftOutputBulkExec/tRedshiftOutputBulkExec_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftRow/tRedshiftRow_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_begin.javajet
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_java.xml
  main/plugins/org.talend.designer.components.localprovider/components/tRedshiftUnload/tRedshiftUnload_messages.properties
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Input/HelpClass.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/DB/Row/HelpClass.javajet
  main/plugins/org.talend.designer.components.localprovider/components/templates/Log4j/Log4jDBConnUtil.javajet
  main/plugins/org.talend.repository/plugin.xml
  main/plugins/org.talend.repository/src/main/java/org/talend/repository/model/migration/RedshiftVersion2MigrationTask.java
Labels: Need review, backport

#7425 fix(TDI-47802): Fix short strings as Clobs
  main/plugins/org.talend.designer.components.localprovider/components/tOracleSP/tOracleSP_main.javajet
Labels: Need review

#7388 fix(TDI-47257): tELTOracleOutput does not print messages during execu…
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_main.javajet
Labels: backport

#7387 fix(TDI-47257): tELTOracleOutput does not print messages during execu…
  main/plugins/org.talend.designer.components.localprovider/components/tELTOracleOutput/tELTOracleOutput_main.javajet
Labels: Need review

#7147 feat(TDI-45629): add dynamic schema support for tFileOutputJSON.
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputJSON/tFileOutputJSON_main.javajet
Labels: Need review

#7486 feat(TDI-45629): add dynamic schema support for tFileOutputJSON.
  main/plugins/org.talend.designer.components.localprovider/components/tFileOutputJSON/tFileOutputJSON_main.javajet
Labels: Need review, backport
